; SUD Workbench — Windows installer (Inno Setup 6.3 or newer).
;
; Built from the payload that packaging/windows/make_win_app.py stages. Compile ON WINDOWS:
;
;     iscc "dist\win\installer\sud-workbench.iss"
;         → dist\win\SUD-Workbench-<version>-win64-setup.exe
;
; Requires Inno Setup 6.3+ for the `x64compatible` architecture identifier (6.2 and earlier spelled
; it `x64`, which 6.3 deprecated). Free, from https://jrsoftware.org/isinfo.php.
;
; ── PREREQUISITES ON THE TARGET MACHINE ─────────────────────────────────────────────────────────
; This installer copies files; the Python environment is built separately (the "prewarm" task below,
; or first launch). That build needs TWO things Windows does not ship, and setup\bootstrap.ps1
; installs either one per-user via winget without an admin prompt, falling back to a plain message
; naming the download:
;
;   · Python 3.12 — the interpreter the app runs on. `winget install Python.Python.3.12`, or
;     python.org. Not 3.13+: the spaCy/thinc (and heavy-tier torch) wheels are pinned to 3.12.
;   · Git — NOT for source control. pip has no built-in git client, and some requirements install
;     from `git+` URLs (wiktra in the core set; spacy-stanza too in the full one), so pip shells out
;     to `git` for them. macOS never noticed this because it always has one; a bare Windows box
;     otherwise spent minutes in pip and then failed on "Cannot find command 'git'".
;     `winget install Git.Git`, or https://git-scm.com/download/win.
;
; Neither is checked HERE, deliberately: blocking the install on them would strand a user who is
; installing now and will be online later, and the same two checks have to exist in the setup
; scripts anyway (the launcher re-runs them whenever the environment is missing). setup\find_py.ps1
; and setup\find_git.ps1 are the single place each is detected.
;
; ── CODE SIGNING IS ABSENT, AND THAT IS VISIBLE TO THE USER ─────────────────────────────────────
; There is no [Setup] SignTool= here because there is no certificate. Consequences, in order of how
; often they will be hit:
;   · Microsoft Defender SmartScreen shows "Windows protected your PC — Unknown publisher" the first
;     time the downloaded setup.exe runs. The user has to click "More info" → "Run anyway". This is
;     a hard stop for a lot of people and is the single biggest reason to buy a certificate.
;   · SmartScreen reputation accrues per signing certificate and per binary hash, so an unsigned
;     installer starts from zero on every release and never accumulates any.
;   · The UAC prompt would say "Unknown publisher" — but this installer never raises one
;     (PrivilegesRequired=lowest), so that particular sting does not apply.
;   · Settings › Apps shows the uninstall entry with no verified publisher.
; An OV certificate clears the prompt only once reputation builds; an EV certificate clears it at
; once. When one exists, add `SignTool=` here and the `signonce` flag to the [Files] entry.

#include "launcher.isi"     ; GENERATED by make_win_app.py: AppVersion, PayloadDir, LauncherKind

#define AppName       "SUD Workbench"
#define AppPublisher  "Siva Kalyan"
#define AppURL        "https://github.com/skalyan91/sud-workbench"
#define ProgId        "SUDWorkbench.conllu"

[Setup]
; A fixed AppId is what ties an upgrade to the previous install's uninstall log; it must never
; change across releases. uuid5(DNS, "io.sunflowerai.sudworkbench") — derived from the same identity
; string the macOS bundle uses as CFBundleIdentifier, so the two platforms are provably one product.
AppId={{B7373AB7-CB8B-55E5-A3B1-12FB42ED8F6D}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}

; PER-USER INSTALL, ALWAYS. `lowest` means Setup never requests elevation, so there is no UAC
; prompt, and {autopf} resolves to {localappdata}\Programs. PrivilegesRequiredOverridesAllowed is
; deliberately NOT set: an all-users install would put the program files under Program Files while
; the venv and the models stayed in each user's own %LOCALAPPDATA%\SUD Workbench (app/paths.py), so
; every additional user would silently rebuild a multi-gigabyte environment of their own. One
; install mode, one data location, no surprises.
PrivilegesRequired=lowest
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
DisableDirPage=auto

; x64compatible, not x64: it also admits ARM64 Windows, which runs x64 binaries under emulation —
; and emulation is exactly what an ARM64 machine needs here, because pythonnet (pywebview's Windows
; backend) publishes no win_arm64 wheel. See the note in requirements-core.txt.
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0

WizardStyle=modern
Compression=lzma2/max
SolidCompression=yes
ChangesAssociations=yes
UninstallDisplayIcon={app}\icon\appicon.ico
SetupIconFile={#PayloadDir}\icon\appicon.ico
LicenseFile={#PayloadDir}\LICENSE.txt
OutputDir=..
OutputBaseFilename=SUD-Workbench-{#AppVersion}-win64-setup

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; Flags: unchecked
Name: "assoc"; Description: "Open .conllu and .conll files with {#AppName}"
; Building the Python environment is a few hundred megabytes of pip work. Doing it here, while the
; user is already watching a progress bar, beats ambushing them on first launch — but it needs the
; network, so it stays optional and its failure is not fatal: the launcher runs the very same script
; again whenever the environment is missing.
Name: "prewarm"; Description: "Set up the Python environment now (recommended; needs an internet connection)"

[Files]
; The whole staged payload, verbatim. make_win_app.py has already removed web/js/dev-fixture.js and
; its <script> tag and trimmed web/fonts to the core faces, so nothing needs excluding here.
Source: "{#PayloadDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Filename/Parameters go through {code:…} rather than a preprocessor macro because the .vbs shape's
; parameter list contains quoted paths, and an Inno parameter that itself contains quotes has to
; have every one of them doubled — nesting that inside an ISPP string literal doubles them again and
; the result is unreadable and unreviewable. Pascal string concatenation says the same thing plainly.
Name: "{autoprograms}\{#AppName}"; Filename: "{code:LauncherExec}"; Parameters: "{code:LauncherParams}"; WorkingDir: "{app}"; IconFilename: "{app}\icon\appicon.ico"
Name: "{autodesktop}\{#AppName}";  Filename: "{code:LauncherExec}"; Parameters: "{code:LauncherParams}"; WorkingDir: "{app}"; IconFilename: "{app}\icon\appicon.ico"; Tasks: desktopicon

[Registry]
; HKA = HKLM in administrative install mode, HKCU otherwise. Under PrivilegesRequired=lowest it is
; always HKCU; HKA is still the right thing to write, because it keeps the script correct if the
; privilege policy is ever relaxed.
;
; OpenWithProgids registers us as *a* handler (so we appear in "Open with" and in the shell's
; association prompt) without claiming the default. The bare default value on the extension is set
; as well, and takes effect only where nothing else has claimed it — a per-user DEFAULT association
; on Windows 8+ is protected by a UserChoice hash no installer can legitimately forge. So: fresh
; machine → we open .conllu; machine with an existing handler → we appear in the list and the user
; chooses. ChangesAssociations=yes above makes Setup call SHChangeNotify when it finishes, so
; Explorer picks up the new icon without a sign-out.
Root: HKA; Subkey: "Software\Classes\{#ProgId}"; ValueType: string; ValueName: ""; ValueData: "CoNLL-U treebank"; Flags: uninsdeletekey; Tasks: assoc
Root: HKA; Subkey: "Software\Classes\{#ProgId}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\icon\appicon.ico,0"; Tasks: assoc
Root: HKA; Subkey: "Software\Classes\{#ProgId}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "{code:OpenCommand}"; Tasks: assoc

Root: HKA; Subkey: "Software\Classes\.conllu\OpenWithProgids"; ValueType: string; ValueName: "{#ProgId}"; ValueData: ""; Flags: uninsdeletevalue; Tasks: assoc
Root: HKA; Subkey: "Software\Classes\.conllu"; ValueType: string; ValueName: ""; ValueData: "{#ProgId}"; Flags: uninsdeletevalue; Tasks: assoc
Root: HKA; Subkey: "Software\Classes\.conll\OpenWithProgids";  ValueType: string; ValueName: "{#ProgId}"; ValueData: ""; Flags: uninsdeletevalue; Tasks: assoc
Root: HKA; Subkey: "Software\Classes\.conll";  ValueType: string; ValueName: ""; ValueData: "{#ProgId}"; Flags: uninsdeletevalue; Tasks: assoc

[Run]
; Pre-warm the environment. runhidden + waituntilterminated: setup_venv.ps1 without -Gui raises no
; window of its own, so Inno's StatusMsg is the only progress on screen, which is what we want
; inside the wizard. Inno does not treat a non-zero [Run] exit code as an error, so a machine with
; no Python 3.12 (that script's `exit 1`) simply finishes the install and defers the work to first
; launch, where bootstrap.ps1 can install Python in a visible console.
Filename: "powershell.exe"; \
  Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\setup\setup_venv.ps1"""; \
  StatusMsg: "Setting up the Python environment (this can take a few minutes)…"; \
  Flags: runhidden waituntilterminated; Tasks: prewarm

Filename: "{code:LauncherExec}"; Parameters: "{code:LauncherParams}"; WorkingDir: "{app}"; \
  Description: "{cm:LaunchProgram,{#AppName}}"; Flags: nowait postinstall skipifsilent

[Code]
{ ── launcher shape ───────────────────────────────────────────────────────────────────────────────
  make_win_app.py stages ONE of two console-free launcher shapes and records which in launcher.isi:
  a compiled GUI-subsystem "SUD Workbench.exe", or launcher.vbs driven by wscript.exe (also a
  GUI-subsystem host). Everything downstream — the two shortcuts, the post-install "Launch" tick and
  the .conllu open command — asks these three functions rather than repeating the branch. }

function LauncherExec(Param: String): String;
begin
#if LauncherKind == "exe"
  Result := ExpandConstant('{app}\{#AppName}.exe');
#else
  Result := ExpandConstant('{sys}\wscript.exe');
#endif
end;

function LauncherParams(Param: String): String;
begin
#if LauncherKind == "exe"
  Result := '';
#else
  { //nologo suppresses the WSH banner; the script path is quoted because {app} can contain spaces
    (it does by default: …\Programs\SUD Workbench). }
  Result := '//nologo "' + ExpandConstant('{app}\launcher.vbs') + '"';
#endif
end;

function OpenCommand(Param: String): String;
begin
  { The verb registered for .conllu. "%1" stays literal — the shell substitutes the document path,
    and it is quoted so a path with spaces arrives as one argument. }
  Result := '"' + LauncherExec('') + '"';
  if LauncherParams('') <> '' then
    Result := Result + ' ' + LauncherParams('');
  Result := Result + ' "%1"';
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DataDir: String;
begin
  { A clean uninstall leaves %LOCALAPPDATA%\SUD Workbench alone: it holds the Python environment,
    the downloaded parser models (the Stanza tier alone runs past a gigabyte) and the user's
    settings and recent files. Removing it by default would turn every reinstall into a
    multi-gigabyte re-download. Inno only deletes what it installed under {app}, so that default is
    already correct and this handler exists purely to OFFER the removal.

    An opt-in Yes/No confirmation rather than a checkbox on a page: Inno's uninstaller has no custom
    wizard pages (CreateInputOptionPage is installer-only), so a real checkbox would mean grafting a
    control onto UninstallProgressForm at run time — more moving parts, none of them testable from a
    macOS build box. MB_DEFBUTTON2 makes "No" the default, so Enter or a reflexive click keeps the
    data and removal happens only on a deliberate "Yes". Skipped entirely under /SILENT, where there
    is nobody to ask and destroying data unasked would be indefensible. }
  if CurUninstallStep = usPostUninstall then begin
    DataDir := ExpandConstant('{localappdata}\{#AppName}');
    if DirExists(DataDir) and (not UninstallSilent) then begin
      if MsgBox('Also delete SUD Workbench''s data folder?' #13#10#13#10
                + DataDir + #13#10#13#10
                + 'It contains the Python environment, any parser models you downloaded (these can '
                + 'be several gigabytes) and your settings and recent files.' #13#10#13#10
                + 'Keep it if you might reinstall — SUD Workbench will find the models again.',
                mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES then
        DelTree(DataDir, True, True, True);
    end;
  end;
end;
