"""Render this app's macOS titlebar SF Symbols to a generated, git-ignored CSS file.

BACKGROUND. Apple licenses SF Symbols for use *within apps on Apple platforms* -- not for
redistribution as standalone assets. Earlier commits baked each symbol's render straight into
web/macos-kit/mac-tokens.css as a literal ``data:image/png;base64,...`` custom property, which
put Apple's rendered artwork in this repo's own git history on every tuning pass (weight/size
fix -> full ~2-4 KB base64 blob re-committed). This module stops that going forward: the SAME
seven symbols are rendered fresh, on demand, into a file this repo's .gitignore excludes, and
mac-tokens.css merely ``@import``s it. Nothing about the on-screen result changes.

THE SEVEN TOKENS + THEIR PARAMETERS. Every one of these went through a careful, measured
weight/size correction earlier this session (see ``git log --oneline -- web/macos-kit/mac-tokens.css``);
the (symbol name, point size, weight) triples below are transcribed verbatim from those commits'
own final, confirmed-correct state -- NOT re-derived -- and this module's own byte-for-byte replay
check (see ``_selftest`` below, exercised by packaging/render_sf_symbols.py) confirms every one
reproduces the exact payload that was, until this change, committed to mac-tokens.css:
  * --sf-undo/--sf-redo/--sf-zoomin/--sf-zoomout/--sf-actualsize/--sf-help: commit 446aebd
    ("Restore real SF-Symbol PNGs for undo/redo/zoom/help titlebar icons") -- arrow.uturn.backward/
    -forward, plus/minus.magnifyingglass, 1.magnifyingglass, questionmark.circle, all at
    96pt/.regular.
  * --sf-grid: commit 059b53e ("Fix --sf-grid: was baked at medium weight, not the regular")
    landed tablecells at 96pt/.regular; c34311c's intervening medium-weight swap was superseded
    by that fix and 3865de0 re-confirmed regular is still correct (measured stroke/bbox ratio
    0.093, inside the family band).

NOT in this table -- deliberately: --sf-open is ALSO a real SF-Symbol PNG baked in
mac-tokens.css, but it predates this session entirely (present already in the initial commit)
and no commit ever recorded its symbol name/weight/size. Guessing risks exactly the silent
regression this module exists to prevent, so it is left exactly as it was -- still literal
base64 in mac-tokens.css, out of scope for this pass. (Its three siblings --sf-new/--sf-append/
--sf-save were in the same boat identity-wise, but a later pass found zero consumers of any of
the three anywhere in the codebase -- unlike --sf-open, which is the real fallback folder glyph
in the titlebar proxy menu and the Save-As sheet's Where popover -- so those three were removed
outright as genuinely dead weight rather than left unidentified.) Likewise the model
manager's cube.box (and addtext/paged/unpaged/options): those were NEVER baked into mac-tokens.css
at all -- app/mac/shell.py's own ``_compute_symbol_icon`` already renders them fresh at every app
launch (64pt/.medium/scale 2), so there is no committed payload to remove there in the first place.

THE RENDER TECHNIQUE. ``NSImage.imageWithSystemSymbolName_accessibilityDescription_`` +
``NSImageSymbolConfiguration.configurationWithPointSize_weight_`` is the same call this session's
own fix commits used and app/mac/shell.py's ``_compute_symbol_icon`` still uses at runtime -- but
rendering it out via ``NSImage.lockFocus()`` (as those commits' own throwaway splice scripts did)
silently follows the CURRENT MACHINE's own screen backing-scale factor: on a Retina build machine
that is 2x, which renders every symbol at DOUBLE the previously-committed pixel dimensions --
confirmed live in this session (a lockFocus render of tablecells at 96pt/.regular came out
270x200 here, not the committed 135x100). The fix is to draw into an explicitly-sized
``NSBitmapImageRep`` bound to its own ``NSGraphicsContext`` instead, which is scale-machine-
independent: verified byte-for-byte identical to the previously-committed payload for all seven
tokens above, on this machine, before they were ever removed from mac-tokens.css.
"""

from __future__ import annotations

import base64
import os

WEB_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "web")
OUT_PATH = os.path.join(WEB_DIR, "macos-kit", "mac-tokens-sf.generated.css")

# token -> (SF Symbol name, point size, NSFontWeight* name). See module docstring for provenance.
SYMBOLS: dict[str, tuple[str, float, str]] = {
    "--sf-undo":       ("arrow.uturn.backward", 96.0, "Regular"),
    "--sf-redo":       ("arrow.uturn.forward",  96.0, "Regular"),
    "--sf-zoomin":     ("plus.magnifyingglass", 96.0, "Regular"),
    "--sf-zoomout":    ("minus.magnifyingglass", 96.0, "Regular"),
    "--sf-actualsize": ("1.magnifyingglass",    96.0, "Regular"),
    "--sf-help":       ("questionmark.circle",  96.0, "Regular"),
    "--sf-grid":       ("tablecells",           96.0, "Regular"),
}

_HEADER = (
    "/* GENERATED by app/mac/sf_symbols.py (packaging/render_sf_symbols.py at package time) --\n"
    "   DO NOT EDIT, DO NOT COMMIT (see .gitignore). Regenerate with:\n"
    "     .venv/bin/python packaging/render_sf_symbols.py\n"
    "   See app/mac/sf_symbols.py's own docstring for what these seven tokens are and why they\n"
    "   live here instead of in mac-tokens.css. */\n"
)


def _render_png_data_uri(AppKit, symbol_name: str, point_size: float, weight_name: str) -> str | None:
    """Render one SF Symbol to a ``data:image/png;base64,...`` URI at an explicit 1x pixel scale
    (see module docstring for why NOT ``NSImage.lockFocus()``). Returns None if this AppKit has no
    SF Symbols support at all (pre-Big Sur) or the name doesn't resolve."""
    NSImage = AppKit.NSImage
    if not hasattr(NSImage, "imageWithSystemSymbolName_accessibilityDescription_"):
        return None
    base = NSImage.imageWithSystemSymbolName_accessibilityDescription_(symbol_name, None)
    if base is None:
        return None
    weight = getattr(AppKit, f"NSFontWeight{weight_name}")
    cfg = AppKit.NSImageSymbolConfiguration.configurationWithPointSize_weight_(point_size, weight)
    img = base.imageWithSymbolConfiguration_(cfg) or base
    size = img.size()
    w, h = max(1, int(round(size.width))), max(1, int(round(size.height)))

    rep = AppKit.NSBitmapImageRep.alloc().initWithBitmapDataPlanes_pixelsWide_pixelsHigh_bitsPerSample_samplesPerPixel_hasAlpha_isPlanar_colorSpaceName_bytesPerRow_bitsPerPixel_(
        None, w, h, 8, 4, True, False, AppKit.NSDeviceRGBColorSpace, 0, 0)
    rep.setSize_((w, h))   # size == pixel dims -> forces 1x, independent of the host screen's own backing scale
    ctx = AppKit.NSGraphicsContext.graphicsContextWithBitmapImageRep_(rep)
    AppKit.NSGraphicsContext.saveGraphicsState()
    AppKit.NSGraphicsContext.setCurrentContext_(ctx)
    try:
        rect = ((0.0, 0.0), (float(w), float(h)))
        img.drawInRect_fromRect_operation_fraction_respectFlipped_hints_(
            rect, ((0.0, 0.0), (0.0, 0.0)), AppKit.NSCompositingOperationSourceOver, 1.0, True, None)
    finally:
        AppKit.NSGraphicsContext.restoreGraphicsState()
    png = rep.representationUsingType_properties_(getattr(AppKit, "NSBitmapImageFileTypePNG", 4), {})
    if png is None:
        return None
    return "data:image/png;base64," + base64.b64encode(bytes(png)).decode("ascii")


def generate(out_path: str = OUT_PATH) -> bool:
    """Render all seven tokens fresh and write ``out_path``. Returns True if every symbol rendered;
    on any failure (non-mac, AppKit missing, a symbol name no longer resolving) writes an EMPTY-but-
    valid stylesheet instead, so mac-tokens.css's own ``@import`` never 404s, and returns False."""
    try:
        import AppKit
    except ImportError:
        AppKit = None

    lines = [_HEADER, ":root{"]
    ok = AppKit is not None
    if ok:
        for token, (name, pt, weight) in SYMBOLS.items():
            uri = _render_png_data_uri(AppKit, name, pt, weight)
            if uri is None:
                ok = False
                continue
            lines.append(f'  {token}:url("{uri}");')
    lines.append("}\n")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    return ok


def ensure(out_path: str = OUT_PATH) -> bool:
    """Dev-convenience on-demand generation (mirrors app/fonts.py's own cached_path/fetch shape):
    if the generated file is already there and looks like a real render (not the empty fallback
    ``generate`` writes on failure -- same ">1024 bytes" cache-sanity floor app/fonts.py's own
    cached_path uses), do nothing. Packaging already produced it, or a previous launch did. Only
    (re-)render when it's missing or empty, so a normal dev launch never pays the render cost more
    than once, but a machine where a prior attempt failed (no AppKit, symbol renamed) keeps retrying
    rather than wedging on a permanent empty stylesheet. Returns True if the file holds a real
    render afterward, False if generation was attempted and still couldn't produce one."""
    if os.path.exists(out_path) and os.path.getsize(out_path) > 1024:
        return True
    return generate(out_path)
